### ISSUE TITLE
Setting for Dock to be always visible (Windows Go Below)

### ISSUE THREAD

**Issue by halverneus** [psifidotos/nowdock-panel#27]
Feature request for replicating the panel settings behavior of "Windows Go Below" whereby the dock is always visible, partially covering the active application (without being inside a transparent panel so that click-through is preserved).

**Comment by psifidotos** [comment]
I suppose what you request is that in the trasparent areas of the panel the mouse signals should go underneath the panel? is that correct?

**Comment by halverneus** [comment]
That would be ideal, though I could live without it. I'm just unable to have an open window behind the dock, so that the dock is always visible, even with a full screen application. Using a transparent panel prevents click-through in a much larger percentage of the screen than I would like. I'm not sure if this request is possible, but I thought I would make it, anyway.

**Comment by psifidotos** [comment]
This is relevant to #8  and #4  which are going upstream (plasma code)... 

The only solution for this would be a transparent panel that has always the minimum needed size for width and height. That would mean for an horizontal panel for example:
1. width would grow and shrink according to its contents
2. height would grow only when a hovering animation is needed
3. all these grows and shrinks wouldnt break the animation and they wouldnt create any visual glitches

unfortunately in current Plasma implementation 1 is supported but it creates the 3 problem and 2 is not provided at all. This is why there arent any news for this yet.

I am in the process to work with the plasma code and developers in order to try to handle this situation but I dont think we can expect something in the near future...

What I am trying to achieve for now is #7 to hit Plasma 5.9.
Hoping for the best... :)

**Comment by halverneus** [comment]
That would be nice! Not sure if anyone has had the thought (or, again, if possible), but a panel that allows visible overflow would be ideal for a ton of use-cases (been a while since I've written in QML, so the painful HTML mindset may be overflowing into this suggestion). This would allow a user to make a 1px tall panel and attach the dock to it, so it inherits the dock's behavior, but isn't confined by the dock's dimensions. Would be super helpful for panel-embedded controls as well (not related).

**Comment by psifidotos** [comment]
a small update in this...

this is not high technology actually... :) There is for Qt Windows a way to set the mask for a window. Which is the area that this window uses and all the other area is not taken into account... It is actually the way Plank and all the other docks are doing it... I will try to cooperate with the plasma devs to add it as a feature in Plasma... We will see... ;)

**Comment by psifidotos** [comment]
https://github.com/psifidotos/nowdock-plasmoid/issues/58

**Comment by halverneus** [comment]
That is EXTREMELY exciting! Can't wait!

**Comment by psifidotos** [comment]
this is in master...

https://github.com/psifidotos/nowdock-plasmoid/issues/58
