### ISSUE TITLE
Panel in autohide mode doesn't appear if plasma configuration also on autohide

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-panel#31]
Hi,

I am trying to put the panel plasma configuration in autohide mode also, along with panel own configuration on autohide.

When this happens, triggering the edge doesn't make the panel appear.

Thanks !

**Comment by psifidotos** [comment]
> I am trying to put the panel plasma configuration in autohide mode also, along with panel own configuration on autohide.

why do you need the plasma panel in autohide mode?

**Comment by alexjp** [comment]
> why do you need the plasma panel in autohide mode?

To not cut desktop space ( plasma does it, makes it impossible to put widgets there then ).

and this ... I hate this ! The bottom empty space beneath the activity explorer

![screenshot_20161130_114355](https://cloud.githubusercontent.com/assets/85806/20751177/4dad20c6-b6f2-11e6-91da-c1538fcd3ff5.png)

**Comment by psifidotos** [comment]
> To not cut desktop space ( plasma does it, makes it impossible to put widgets there then ).
> and this ... I hate this ! The bottom empty space beneath the activity explorer

try this.... set the plasma panel's height to minimum!!!! Dont worry that Now Dock icons are not showing at that step, when you lock your widgets everything will look ok... that space you hate will be reduced except of 16pxs from the bottom... For this nothing else can be done... Except maybe if the "Auto-Hide" behavior is used also for "Windows can cover" inside the plasma code...

**Comment by psifidotos** [comment]
ok... I uploaded a small patch in order to help you with this...

but you need a small trick also...  the patch loads the Now Dock panel immediately so there is a chance that you miss a sliding-in animation that way... after that, the Now Dock works ok with Auto-Hide (both Now Dock and Plasma Panel)..

BUT be careful in this: If you unlock your widgets in order to add something in your desktop or etc... You must lock them again from inside the Now Dock Panel (when you are **locking** your widgets **the Now Dock Panel should not be hidden !!!**)... This is enough to give you the experience you want.... I hope in the future that I will come up with something better...

**Comment by psifidotos** [comment]
@alexjp I think that with this patch everything is going to work ok .... Forget all the above!! :)

**Comment by alexjp** [comment]
Its not working very well here. I mean ... it works well, but not always.

Actually ... testing it more, seems only works on first virtual desktop

**Comment by psifidotos** [comment]
> Actually ... testing it more, seems only works on first virtual desktop

lock/unlock widgets and it should be ok...

something with the initialization... I believe I will find it...

**Comment by psifidotos** [comment]
https://github.com/psifidotos/nowdock-panel/issues/32

**Comment by psifidotos** [comment]
latest commit, works for me ok with alldesktops...

**Comment by alexjp** [comment]
Yes ... can close i think ... works good also !

Even with plasma panel autohide but nowdock "behind windows". :) like plasma panel should be.

**Comment by psifidotos** [comment]
nice! Let's leave it for some days open, if not anything else arise we can close it then....
