### ISSUE TITLE
Folderview applet animation

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/nowdock-panel#44]
Plasma 5.8.90
Versione Qt: 5.7.1
KDE Frameworks 5.30.0
Wayland

On Folderview applet, animation is not smooth
wrong icons resizeing

**Comment by psifidotos** [comment]
wayland? 
does Now Dock work on wayland?

concerning the folderview this is a folderview concern, Now Dock does not interfere with the plasmoids internals. Personally for my folderview applet I lock it in order to not animate at all and I place it far left or right to my dock...

**Comment by JenaPlinsky** [comment]
Yes I'm using Wayland
launcher menu animation applets do not work propely
while the animation of the weather applet is smooth
I think, it would be nice to have all the applets animations including therefore the folderview it 's very comfortable use as a category of programs on nowdock.

Not implement for technical issues or by choice?

**Comment by psifidotos** [comment]
It is applets' bug, not Now Dock's, I cant do anything in Now Dock to fix
this... Those maintaining the applets must find a way to handle the Now
Dock animation... You can report them the issue...

Στις 16 Δεκ 2016 01:03, ο χρήστης "JenaPlinsky" <notifications@github.com>
έγραψε:

Yes I'm using Wayland
launcher menu animation applets do not work propely
while the animation of the weather applet is smooth
I think, it would be nice to have all the applets animations including
therefore the folderview it 's very comfortable use as a category of
programs on nowdock.

Not implement for technical issues or by choice?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/psifidotos/nowdock-panel/issues/44#issuecomment-267470380>,
or mute the thread
