### ISSUE TITLE
Panel animation is independent of dock

### ISSUE THREAD

**Issue by rokups** [psifidotos/nowdock-panel#47]
None of panel visibility options seem to make it work as one would expect. Main issue is panel animating independently of dock giving away the fact that they are independent entities. It would be great if they both animated together in a lockstep giving impression that panel is part of the dock (anchored to the edge of the dock). Now in some cases either panel or dock may remain visible without the other one in the view. I think panel is meant to act as a background for dock dots/strips, but when its gone it all looks bad.

For now im using "windows go below" panel option as it works most correct, but that tiny panel strip is always visible. Would be great if we could get rid of that.

**Comment by psifidotos** [comment]
In order to hide the plasma's panel you need a plasma theme that creates transparency for that specific panel... You can use the trasparent panel script that can help you with that please read the information at the store.kde.org page of Now Dock. 

For plasma 5.9 this step is not needed at all...

**Comment by rokups** [comment]
This is exactly what i did. Without using that script panel would be big fat encompassing entire dock. After using transparent panel script i could reduce panel height to about 20px and it no longer cut-off the dock, however that 20px high panel is still visible like in official screenshots. I attached screenshot. Above with dock visible and below is panel always visible but dock hidden.

![example](https://cloud.githubusercontent.com/assets/19151258/21256987/5c5f058a-c36d-11e6-862f-c5426c533a61.png)

**Comment by psifidotos** [comment]
In case you used the script and you have chosen the Now produced theme with
trasparency, have you disabled the blur and contrast desktop effects? You
dont need to shrink the panel's height, it is done automatically when the
widgets are locked...

Στις 16 Δεκ 2016 10:55 π.μ., ο χρήστης "Rokas Kupstys" <
notifications@github.com> έγραψε:

This is exactly what i did. Without using that script panel would be big
fat encompassing entire dock. After using transparent panel script i could
reduce panel height to about 20px and it no longer cut-off the dock,
however that 20px high panel is still visible like in official screenshots.
I attached screenshot. Above with dock visible and below is panel always
visible but dock hidden.

[image: example]
<https://cloud.githubusercontent.com/assets/19151258/21256987/5c5f058a-c36d-11e6-862f-c5426c533a61.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/psifidotos/nowdock-panel/issues/47#issuecomment-267547042>,
or mute the thread

**Comment by rokups** [comment]
Oh, that was it - desktop effects needed to be disabled. Now i understand whats going on. I misinterpreted visible panel as proper behavior because i could get it look like in screenshots. Sorry for the noise.

**Comment by psifidotos** [comment]
dont worry!!! I hope u like it...

Στις 16 Δεκ 2016 12:00 μ.μ., ο χρήστης "Rokas Kupstys" <
notifications@github.com> έγραψε:

**Comment by rokups** [comment]
I love it ;) For kde its better than anything. Thanks :)
