### ISSUE TITLE
Show only tasks ftom the current activities

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/nowdock-panel#59]
The option [ now dock settings] [ Interaction ] [ show only tasks ftom the current activities ] is currently ignored

**Comment by psifidotos** [comment]
It doesnt occur in my System... Are you changing activities and you are
shown windows from windows that do not belong in the current activity?

Στις 21 Δεκ 2016 20:32, ο χρήστης "JenaPlinsky" <notifications@github.com>
έγραψε:

The option [ now dock settings] [ Interaction ] [ show only tasks ftom the
current activities ] is currently ignored

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/psifidotos/nowdock-panel/issues/59>, or mute the thread

**Comment by JenaPlinsky** [comment]
If I launch "blender" from the activity "graphics" and then return to "office" it will still appear. I remind you that I am using the unstable version 4.8.90 and I noticed that the button "stiky, do not know his exact name" that is present on all windows, top left side, oddly enough, is always active and there is no way turn it off, but this should replicate the opened app on virtual desktops right? this should not interact with the activities? maybe it's a bug kwin

**Comment by psifidotos** [comment]
this is not happening in my system for "blender"...

>  I noticed that the button "stiky, do not know his exact name" that is present on all windows, top left side, oddly enough, is always active and there is no way turn it off,

this means that an explicit rule in kwin has been set for this window to be on all activities and on all desktops probably...

you could use the window titlebar to access the special settings for the window or the application and checkout that such rule does not exist...
